Repository bluestoneag/log4j-collector-frontend, pull requests merged in 2021-12, with the labels that each got.

#4 Add Download CSV button
  src/components/Body.tsx
  src/components/Button.tsx
  src/components/Search.tsx
Labels: documentation, enhancement

#5 fix dockerfile and add env support
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .gitignore
  Dockerfile
  README.md
  assets/dashboard.jpg
  assets/dashboard.png
  assets/searchjpg.jpg
  conf/conf.d/default.conf
  conf/conf.d/gzip.conf
  docker-compose.yml
  env.sh
  package-lock.json
  package.json
  public/index.html
  src/components/Body.tsx
  src/components/Head.tsx
  src/components/Logo.tsx
  yarn.lock
Labels: bug, documentation, enhancement

#6 fix env part
  README.md
Labels: documentation

#7 fix image path
  README.md
Labels: documentation

#14 add file search checkbox
  src/components/Body.tsx
Labels: enhancement
